title: <p align="center"> NLTR </p>
logo: /assets/img/logo.png
description:  <p align="center">
                <a href="https://www.linkedin.com/in/nishantawasthi007/">LinkedIn</a> |
                <a href="https://github.com/nltr2">GitHub</a>
                <br>   
                I have 13 years of experience in web application development.
                <br>
              </p>

theme: jekyll-theme-minimal
