title: <p align="center"> NLTR </p>
logo: /assets/img/logo.jpg
description:  
<p align="center">
  <!-- <a href="pdf/resume.pdf">Resume</a> | -->
  <a href="https://www.linkedin.com/in/nishantawasthi007/">LinkedIn</a> |
  <a href="https://github.com/nltr2">GitHub</a>
  
  <br>   
  I have 13 years of experience in web application development.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
